### PR TITLE
Deprecate jsoncdc in favor of instructure/jsoncdc

### PR DESCRIPTION
**Pull request by Mythra**
After some talk in a Github Pull Request [HERE](https://github.com/instructure/jsoncdc/pull/2), and in twitter DMs, it was decided we'd point to `instructure/jsoncdc` as the source repository for jsoncdc (since we had some changes we hadn't yet pull requested). 

This commit marks this repository as officially deprecated. Once we publish the new extension on pgxn (and publish our internal debian packages) we will most likely start taking a look at officially maintaining rpgffi as well.

The new repository contains one new version that isn't available in this source repository (published as version `0.0.12`, and the newer documentation `v0.1.0`. When we release our debian package code we will build all the old versions (and we have no intention of removing history/or the old extensions from pgxn.)

### CODE REVIEW

**Comment by Mythra** [comment]
Preferabbly we we squash and merge this to not ink up history when we deprecate.

**Comment by posix4e** [comment]
@solidsnack You ok with any or all of this?

**Comment by solidsnack** [comment]
Maybe I am reading this wrong but shouldn’t there be a message in the README to the effect that this is deprecated?

**Comment by Mythra** [comment]
Hey @solidsnack ,

That's what I've left. A Message in the readme pointing to the instructure/jsoncdc repo (and making note how the previous code is still available in git history). I'm happy to change it to be more of a longer winded message, or something else entirely.

**Comment by solidsnack** [comment]
Okay, I am looking at how is on a phone. Let me look again.
Eric <notifications@github.com> schrieb am Do. 22. März 2018 um 15:00:

**Comment by solidsnack** [comment]
Closed in favor of: d451cb12614661abaafc52136146b3a557244044

@posix4e We should update the repo description ("Takes a logical decoding...") to mention the new repo so it's right there at the top.

**Pull request closed without merging**
